### PR TITLE
Use relative path in generated settings.json

### LINKED ISSUE #181: Use ${workspaceFolder} instead of absolute path in workspace config
Currently flatpak-vscode writes something like this to the workspace config:

```
    "mesonbuild.mesonPath": "/home/rasmus/Projects/Health/.flatpak/meson.sh",
    "rust-analyzer.server.path": "/home/rasmus/Projects/Health/.flatpak/rust-analyzer.sh",
    "rust-analyzer.runnables.command": "/home/rasmus/Projects/Health/.flatpak/cargo.sh",
```

This causes other contributors to have a diff because their homefolder is used. It'd be nice if ${workspaceFolder} was used so this diff doesn't happen:

```
    "mesonbuild.mesonPath": "${workspaceFolder}/.flatpak/meson.sh",
    "rust-analyzer.server.path": "${workspaceFolder}/.flatpak/rust-analyzer.sh",
    "rust-analyzer.runnables.command": "${workspaceFolder}/.flatpak/cargo.sh",
```

### PR DESCRIPTION
**Pull request by caspermeijn**
Fixes #181

### CODE REVIEW

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Would you mind updating the changelog as well?

**Comment by SeaDve** [comment]
It was done slightly different before, but reverted due to rust analyzer issues. 

https://github.com/bilelmoussaoui/flatpak-vscode/pull/184

I wonder if it still causes the issue

**Comment by caspermeijn** [comment]
@SeaDve Do you know what the issue was? Then I can test for those. I have seen that rust analyzer performs auto completion, but I have not done extensive usage.

**Comment by SeaDve** [comment]
> @SeaDve Do you know what the issue was? Then I can test for those. I have seen that rust analyzer performs auto completion, but I have not done extensive usage.

I don't really remember, but since rust analyzer seems to run, the issue has been probably fixed.

To be more sure, maybe you can also test runnables, like the `Run test` that appears on the text editor

**Review by SeaDve — APPROVED** [review]

**Comment by caspermeijn** [comment]
@SeaDve I can confirm that `Run test` works. It starts via `cargo.sh`.

**Comment by nahuelwexd** [comment]
Uhm... are you sure this works? I just updated and now I can't use the Vala language server, as it keeps returning ENOENT error, that the vala-language-server.sh does not exist

**Comment by caspermeijn** [comment]
> Uhm... are you sure this works? I just updated and now I can't use the Vala language server, as it keeps returning ENOENT error, that the vala-language-server.sh does not exist

Well, I have not tested Vala. @bilelmoussaoui Was this the reason of the revert last time around?

**Comment by nahuelwexd** [comment]
@caspermeijn The previous time it was tried, it was reverted because the Rust analyzer was failing for the same reasons that the Vala extension is failing now

Look at the issue I opened: #215

It seems to me that the Rust analyzer no longer fails because the extension that launches it is manually resolving the `workspaceFolder` variable

**Comment by caspermeijn** [comment]
I tested the meson integration. That seems to function fine with the change. Lets continue the conversation in #215 for a fix of the Vala language server.

**Pull request merged**
