### PR TITLE
migration: fix the manifest path

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I will do another release once this one lands

**Comment by SeaDve** [comment]
What's the difference between `Uri.fsPath` and `Uri.path`?

**Comment by bilelmoussaoui** [comment]
Well in this case it is not a URI, it is a json file

**Comment by bilelmoussaoui** [comment]
The pipeline state file looks like this in general
```json
{
    "loaded": true,
    "selectedManifest": {
        "uri": {
            "$mid": 1,
            "external": "file:///var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
            "path": "/var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
            "scheme": "file"
        },
        "manifest": "...",
        "workspace": "/var/home/bilelmoussaoui/Projects/d-spy",
        "buildDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak",
        "repoDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/repo",
        "stateDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/flatpak-builder",
        "stateFile": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/pipeline.json"
    },
    "manifests": [
        {
            "uri": {
                "$mid": 1,
                "external": "file:///var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
                "path": "/var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
                "scheme": "file"
            },
            "manifest": {
                "app-id": "org.gnome.dspy.devel",
                "runtime": "org.gnome.Platform",
                "runtime-version": "master",
                "sdk": "org.gnome.Sdk",
                "command": "d-spy",
                "finish-args": [
                    "--device=dri",
                    "--socket=fallback-x11",
                    "--socket=wayland",
                    "--socket=session-bus",
                    "--socket=system-bus"
                ],
                "cleanup": [
                    "/include",
                    "/lib/pkgconfig",
                    "/man",
                    "/share/doc",
                    "/share/gtk-doc",
                    "/share/man",
                    "/share/pkgconfig",
                    "*.la",
                    "*.a"
                ],
                "modules": [
                    {
                        "name": "d-spy",
                        "builddir": true,
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Ddevelopment=true"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/d-spy.git",
                                "branch": "main"
                            }
                        ]
                    }
                ]
            },
            "workspace": "/var/home/bilelmoussaoui/Projects/d-spy",
            "buildDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak",
            "repoDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/repo",
            "stateDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/flatpak-builder",
            "stateFile": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/pipeline.json"
        },
        {
            "uri": {
                "$mid": 1,
                "fsPath": "/var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
                "external": "file:///var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
                "path": "/var/home/bilelmoussaoui/Projects/d-spy/org.gnome.dspy.devel.json",
                "scheme": "file"
            },
            "manifest": {
                "app-id": "org.gnome.dspy.devel",
                "runtime": "org.gnome.Platform",
                "runtime-version": "master",
                "sdk": "org.gnome.Sdk",
                "command": "d-spy",
                "finish-args": [
                    "--device=dri",
                    "--socket=fallback-x11",
                    "--socket=wayland",
                    "--socket=session-bus",
                    "--socket=system-bus"
                ],
                "cleanup": [
                    "/include",
                    "/lib/pkgconfig",
                    "/man",
                    "/share/doc",
                    "/share/gtk-doc",
                    "/share/man",
                    "/share/pkgconfig",
                    "*.la",
                    "*.a"
                ],
                "modules": [
                    {
                        "name": "d-spy",
                        "builddir": true,
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Ddevelopment=true"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/d-spy.git",
                                "branch": "main"
                            }
                        ]
                    }
                ]
            },
            "workspace": "/var/home/bilelmoussaoui/Projects/d-spy",
            "buildDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak",
            "repoDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/repo",
            "stateDir": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/flatpak-builder",
            "stateFile": "/var/home/bilelmoussaoui/Projects/d-spy/.flatpak/pipeline.json"
        }
    ],
    "pipeline": {
        "latestStep": "rebuild",
        "error": null,
        "initialized": true,
        "dependencies": {
            "updated": true,
            "built": true
        },
        "application": {
            "built": true
        }
    }
}
```

**Comment by SeaDve** [comment]
Won't this be problematic with other `fsPath` accesses

**Comment by bilelmoussaoui** [comment]
> I think other other `fsPath` accesses might cause problems like this

Well not really, this is specific to the migration because the pipeline state file doesn't have a `selectedManifest -> uri -> fsPath` instead it only have a `selectedManifest -> uri -> path` that is how a Uri is serialized to JSON. 

We don't have any other use case like this in the extension IIRC

**Comment by SeaDve** [comment]
For some reason the manifest's uri for `org.gnome.SoundRecorder` is serialized with fsPath

```json
{
    "loaded": false,
    "selectedManifest": {
        "uri": {
            "$mid": 1,
            "fsPath": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
            "external": "file:///home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
            "path": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
            "scheme": "file"
        },
        "manifest": {
            "app-id": "org.gnome.SoundRecorderDevel",
            "runtime": "org.gnome.Platform",
            "runtime-version": "41",
            "sdk": "org.gnome.Sdk",
            "command": "gnome-sound-recorder",
            "tags": [
                "nightly"
            ],
            "finish-args": [
                "--share=ipc",
                "--device=dri",
                "--socket=fallback-x11",
                "--socket=wayland",
                "--socket=pulseaudio",
                "--filesystem=~/Recordings",
                "--talk-name=org.a11y.Bus"
            ],
            "build-options": {
                "build-args": [
                    "--share=network"
                ]
            },
            "modules": [
                {
                    "name": "libadwaita",
                    "buildsystem": "meson",
                    "config-opts": [
                        "-Dtests=false",
                        "-Dexamples=false",
                        "-Dvapi=false"
                    ],
                    "cleanup": [
                        "/include",
                        "/lib/pkgconfig"
                    ],
                    "sources": [
                        {
                            "type": "git",
                            "url": "https://gitlab.gnome.org/GNOME/libadwaita.git",
                            "branch": "main"
                        }
                    ]
                },
                {
                    "name": "gnome-sound-recorder",
                    "buildsystem": "meson",
                    "config-opts": [
                        "-Dprofile=development"
                    ],
                    "sources": [
                        {
                            "type": "git",
                            "url": "https://gitlab.gnome.org/GNOME/gnome-sound-recorder.git"
                        }
                    ]
                }
            ]
        },
        "workspace": "/home/dave/Projects/gnome-sound-recorder",
        "buildDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak",
        "repoDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/repo",
        "stateDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/flatpak-builder",
        "stateFile": "/home/dave/Projects/gnome-sound-recorder/.flatpak/pipeline.json"
    },
    "manifests": [
        {
            "uri": {
                "$mid": 1,
                "fsPath": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
                "external": "file:///home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
                "path": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorde.json",
                "scheme": "file"
            },
            "manifest": {
                "app-id": "org.gnome.SoundRecorderDevel",
                "runtime": "org.gnome.Platform",
                "runtime-version": "41",
                "sdk": "org.gnome.Sdk",
                "command": "gnome-sound-recorder",
                "tags": [
                    "nightly"
                ],
                "finish-args": [
                    "--share=ipc",
                    "--device=dri",
                    "--socket=fallback-x11",
                    "--socket=wayland",
                    "--socket=pulseaudio",
                    "--filesystem=~/Recordings",
                    "--talk-name=org.a11y.Bus"
                ],
                "build-options": {
                    "build-args": [
                        "--share=network"
                    ]
                },
                "modules": [
                    {
                        "name": "libadwaita",
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Dtests=false",
                            "-Dexamples=false",
                            "-Dvapi=false"
                        ],
                        "cleanup": [
                            "/include",
                            "/lib/pkgconfig"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/libadwaita.git",
                                "branch": "main"
                            }
                        ]
                    },
                    {
                        "name": "gnome-sound-recorder",
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Dprofile=development"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/gnome-sound-recorder.git"
                            }
                        ]
                    }
                ]
            },
            "workspace": "/home/dave/Projects/gnome-sound-recorder",
            "buildDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak",
            "repoDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/repo",
            "stateDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/flatpak-builder",
            "stateFile": "/home/dave/Projects/gnome-sound-recorder/.flatpak/pipeline.json"
        },
        {
            "uri": {
                "$mid": 1,
                "fsPath": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorder.json",
                "external": "file:///home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorder.json",
                "path": "/home/dave/Projects/gnome-sound-recorder/org.gnome.SoundRecorder.json",
                "scheme": "file"
            },
            "manifest": {
                "app-id": "org.gnome.SoundRecorderDevel",
                "runtime": "org.gnome.Platform",
                "runtime-version": "41",
                "sdk": "org.gnome.Sdk",
                "command": "gnome-sound-recorder",
                "tags": [
                    "nightly"
                ],
                "finish-args": [
                    "--share=ipc",
                    "--device=dri",
                    "--socket=fallback-x11",
                    "--socket=wayland",
                    "--socket=pulseaudio",
                    "--filesystem=~/Recordings",
                    "--talk-name=org.a11y.Bus",
                    "--required-version=1.14.0"
                ],
                "build-options": {
                    "build-args": [
                        "--share=network"
                    ]
                },
                "modules": [
                    {
                        "name": "libadwaita",
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Dtests=false",
                            "-Dexamples=false",
                            "-Dvapi=false"
                        ],
                        "cleanup": [
                            "/include",
                            "/lib/pkgconfig"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/libadwaita.git",
                                "branch": "main"
                            }
                        ]
                    },
                    {
                        "name": "gnome-sound-recorder",
                        "buildsystem": "meson",
                        "config-opts": [
                            "-Dprofile=development"
                        ],
                        "sources": [
                            {
                                "type": "git",
                                "url": "https://gitlab.gnome.org/GNOME/gnome-sound-recorder.git"
                            }
                        ]
                    }
                ]
            },
            "workspace": "/home/dave/Projects/gnome-sound-recorder",
            "buildDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak",
            "repoDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/repo",
            "stateDir": "/home/dave/Projects/gnome-sound-recorder/.flatpak/flatpak-builder",
            "stateFile": "/home/dave/Projects/gnome-sound-recorder/.flatpak/pipeline.json"
        }
    ],
    "pipeline": {
        "latestStep": "build-init",
        "error": null,
        "initialized": true,
        "dependencies": {
            "updated": true,
            "built": false
        },
        "application": {
            "built": false
        }
    }
}

```

**Comment by bilelmoussaoui** [comment]
Oh heh, maybe that only happens if using a sandboxed vscode...

**Comment by SeaDve** [comment]
I'll open an issue about it for now, and investigate on it in the future

**Pull request merged**
