### PR TITLE
Use actual build and runtime terminal names

### PR DESCRIPTION
**Pull request by SeaDve**

### CODE REVIEW

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
I suppose we could land this as is and keep a note of that in the readme in a list of known issues so we can revisit that whenever there is an API for opting out of restoring the custom terminals ?

**Comment by SeaDve** [comment]
I think that's good. I'll add it on readme before merging this.

**Comment by SeaDve** [comment]
Well another weirdness, the names are restored properly when there is no `Flatpak: ` prefix.

**Comment by bilelmoussaoui** [comment]
> Another weirdness, the names are restored properly when there is no `Flatpak: ` prefix......
> 
> I guess removing the prefix is a worthy trade off than a terminal with only `Flatpak: ` as name after restore

Sounds good to me

**Pull request merged**
