### PR TITLE
Run yarn upgrade --latest

### PR DESCRIPTION
**Pull request by SeaDve**
Also fixes 2 vulnerabilities according to yarn audit

`yaml.safeLoad` is also renamed to `yaml.load`
https://github.com/nodeca/js-yaml/blob/ab31bba6b41f58390f431123ffec5031b986edf5/migrate_v3_to_v4.md

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
feel free to drop the node10 from the CI

**Comment by SeaDve** [comment]
whoops

**Comment by bilelmoussaoui** [comment]
oh you have to rebase as well, sorry :)

**Comment by SeaDve** [comment]
No problem.

**Pull request merged**
