### PR TITLE
manifest: Add a default PATH fallback

### LINKED ISSUE #212: "/app/bin" is not in PATH
I tried to build Denaro ([manifest](https://github.com/NickvisionApps/Denaro/blob/main/NickvisionMoney.GNOME/org.nickvision.money.json)), but it failed with error:

```
flatpak build --share=network --nofilesystem=host --filesystem=/var/home/user/Проекты/Nickvision/Denaro --filesystem=/var/home/user/Проекты/Nickvision/Denaro/.flatpak/repo --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/sdk/dotnet7/lib/pkgconfig --env=RUST_BACKTRACE=1 --env=PATH=/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/var/home/user/.local/bin:/var/home/user/bin:/var/home/user/.dotnet/tools:/usr/lib/sdk/dotnet7/bin:/usr/lib/sdk/rust-stable/bin --env=LD_LIBRARY_PATH=/app/lib:/usr/lib/sdk/dotnet7/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig /var/home/user/Проекты/Nickvision/Denaro/.flatpak/repo just NickvisionMoney.GNOME/ publish-flatpak
bwrap: execvp just: No such file or directory
```

The last module uses simple build system and runs programs that are installed to `/app/bin` by previous modules, but PATH doesn't contain this directory as can be seen in the command above.
Adding this to manifest helps:

```
"build-options": {
    "append-path": "/app/bin"
},
```

but I wish it worked out of the box just like in GNOME Builder, without workarounds.
I used extension built from the [latest commit](https://github.com/bilelmoussaoui/flatpak-vscode/commit/d36177b5f3d18dc2faa374f099798d4a604de4b5).

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Fixes #212

### CODE REVIEW

**Comment by fsobolev** [comment]
This doesn't work because default value isn't used if PATH exists (and it doesn't contain `/app/bin`), at line 255:
```
const currentValue = process.env[envVariable] || defaultValue
```

Also, I'm very sorry, I wasn't paying enough attention when I said that modifying PATH is enough to make simple build system work 😅 Commands with spaces will fail even for programs that are in PATH, for example `ls /`:
```
bwrap: execvp ls /: No such file or directory
```
To fix this I changed line 517:
```
['build', ...buildArgs, this.repoDir, ...command.split(' ')],
```

Sorry for inconvenience, I would be happy to fix everything myself and open a PR instead of just complaining, but I'm not sure how to properly fix this PATH issue

**Comment by bilelmoussaoui** [comment]
> This doesn't work because default value isn't used if PATH exists (and it doesn't contain `/app/bin`), at line 255:
> 
> ```
> const currentValue = process.env[envVariable] || defaultValue
> ```
> 
> Also, I'm very sorry, I wasn't paying enough attention when I said that modifying PATH is enough to make simple build system work sweat_smile Commands with spaces will fail even for programs that are in PATH, for example `ls /`:
> 
> ```
> bwrap: execvp ls /: No such file or directory
> ```
> 
> To fix this I changed line 517:
> 
> ```
> ['build', ...buildArgs, this.repoDir, ...command.split(' ')],
> ```
> 
> Sorry for inconvenience, I would be happy to fix everything myself and open a PR instead of just complaining, but I'm not sure how to properly fix this PATH issue

I suppose you are running vscode unsandboxed?

**Comment by fsobolev** [comment]
> I suppose you are running vscode unsandboxed?

I run it in Fedora 38 distrobox.

**Comment by bilelmoussaoui** [comment]
Fixed both issues in #214

**Pull request closed without merging**
