### PR TITLE
Pickier parser

### PR DESCRIPTION
**Pull request by SeaDve**

### CODE REVIEW

**Comment by SeaDve** [comment]
Does CI run tests?

**Comment by bilelmoussaoui** [comment]
We should probably run the tests with xvfb-run

**Comment by SeaDve** [comment]
I'll try failing a test if it actually works

**Comment by bilelmoussaoui** [comment]
Something I wonder about, are there apps that uses a flatpak manifest named `flatpak.json`, because we would not pick that manifest at all and the user has no way to select that in #71 isn't it? maybe we could allow selecting a random file there if we don't manage to find one ourselves ?

**Comment by SeaDve** [comment]
> because we would not pick that manifest at all and the user has no way to select that in #71 isn't it?

yep, there won't be a way to select it

> Something I wonder about, are there apps that uses a flatpak manifest named `flatpak.json`

I've not seen one

> maybe we could allow selecting a random file there if we don't manage to find one ourselves ?

Isn't it required to name a manifest to its id? I'm thinking of linking a specification in naming manifest if there is one

**Comment by bilelmoussaoui** [comment]
> But that could work, if naming a manifest file by its id is just a convention

It is only a requirement for Flathub because it assumes the repo name = the file name = the id. Although, maybe worth checking what Builder does here and assume a similar thing so that we are at least consistent on that regard

**Comment by SeaDve** [comment]
Builder does something similar with this (assumes file name is the app id) when looking for manifest.

**Comment by SeaDve** [comment]
Somewhat related to the PR, does flatpak manifest allow `.jsonc` format? The finder glob pattern also finds it triggering invalid document id error at https://github.com/bilelmoussaoui/flatpak-vscode/blob/7eda49aed9e1a1fbe5a182362372b29dc2486602/src/flatpakManifestFinder.ts#L41

**Comment by bilelmoussaoui** [comment]
> Somewhat related to the PR, does flatpak manifest allow `jsonc`? The finder glob pattern also finds it triggering invalid document id error at
> 
> https://github.com/bilelmoussaoui/flatpak-vscode/blob/7eda49aed9e1a1fbe5a182362372b29dc2486602/src/flatpakManifestFinder.ts#L41

Yes because flatpak uses json-glib which allows comments in the json file, that might be problematic because the json parser we use might not like that.... in such case we could probably just  `flatpak-builder --show-manifest` and that would drop the comments from it and we can parse that output instead of reading the json file

**Comment by SeaDve** [comment]
Running a subprocess just for parsing may be slower, we could maybe just use a JSONC parser

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
